### ISSUE TITLE
Grid selected row

### ISSUE THREAD

**Issue by mihaimyh** [gustavnavar/Grid.Blazor#10]
I am unable to see on documentation the way one can get a selected row.

How can this be done?

Thank you for your understanding.

**Comment by gustavnavar** [comment]
I will add a section for the **Selectable** feature.

By default the **Selectable** feature is **true** for Blazor client-side and for Blazor server-side projects.

So you only have to add the **OnRowClicked** atrribute on the component. For example:
```razor
    <GridComponent T="Order" Grid="@_grid" OnRowClicked="@OrderDetails"></GridComponent>
```
Then you have to add the function that calls the event. In this exemple its name is **OrderDetails**:
```c#
    protected void OrderDetails(object item)
    {
        Order order;
        if (item.GetType() == typeof(Order))
        {
            order = (Order)item;
        }
        else
        {
            order = null;
        }
        Console.WriteLine("Order Id: " + order.OrderID.ToString());
    }
```

In the GridBlazor.Demo.Client project you will find another example where the order details are shown on a component when a row is selected.

**Comment by mihaimyh** [comment]
Thank you, it seems to be working as expected.

Is there a way to programatically un-select a row? I would like the visual effect of highlighting the row to disappear.

**Comment by gustavnavar** [comment]
You can add the following lines to your css file:

```css
table.grid-table tr.grid-row-selected td {
    background: transparent !important;
    color: black;
    -webkit-animation-name: change-background;
    -webkit-animation-duration: 5s;
    animation-name: change-background;
    animation-duration: 5s;
}

@-webkit-keyframes change-background {
    from {
        background: #4888C2;
    }

    to {
        background: transparent;
    }
}

@keyframes change-background {
    from {
        background: #4888C2;
    }

    to {
        background: transparent;
    }
}
```
