### ISSUE TITLE
Fixed row height

### ISSUE THREAD

**Issue by martinscholz83** [gustavnavar/Grid.Blazor#141]
How can i set fixed row heights. Currently when paging the Grid always jumps up and down because of different length of content in some cells. Is there a way to set some fixed height with a word-wrapping or so.

**Comment by gustavnavar** [comment]
You can add the following lines to your style sheet:

```css
.grid-cell {
    max-width: 100px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}
```

**Comment by martinscholz83** [comment]
Thx! I thought it has to be managed with one of [these](https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_server/GridBlazor_configuration.md#gridcomponent-parameters) params.

**Comment by gustavnavar** [comment]
You can use the default ```grid-cell``` class as mentioned before

Or you can use the ```GridCellCssClass``` parameter of the ```GridComponent``` object if you want to fully override  the default ```grid-cell``` class and create your own style:

```c#
 <GridComponent GridCellCssClass="this-cell-style"
```

```css
.this-cell-style {
    max-width: 100px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}
```
