### ISSUE TITLE
css / format issues

### ISSUE THREAD

**Issue by rweston415** [gustavnavar/Grid.Blazor#202]
Many of our columns contain data that all has the same width.  Is there a fast easy way for the header and its associated data to be centered for all resolutions? 

Also, is there a fast easy way for the headers and row data to be centered vertically within the row for all resolutions?

**Comment by gustavnavar** [comment]
For headers you can add this to your style sheet:
```css
.grid-header-title {
    text-align: center;
}
```

And for row data this:
```css
.grid-cell {
    text-align: center;
}
```

**Comment by rweston415** [comment]
Thanks for the reply.  I am wanting to only center selected columns in the grid, not all of the columns.  Any help would be greatly appreciated.

**Comment by gustavnavar** [comment]
Then you have to define the column as follows:
```c#
Action<IGridColumnCollection<Order>> OrderColumns = c =>
{
    ...
    var col = c.Add(o => o.Customer.CompanyName).Titled(SharedResource.CompanyName);
     ((GridStyledColumn)col).AddCssClass("center-align");
    ...
}
```

And add the following style:
```css
.center-align {
    text-align: center;
}
```
