### ISSUE TITLE
Change cell background color depending on value.

### ISSUE THREAD

**Issue by jcvw75** [gustavnavar/Grid.Blazor#403]
So far I tried SetCellCssClassesContraint but the css classes I create can only be used for the text color.

I want to be able to change the background color but when i use the background-color: red it doesn't work 
.addPayHold {
    background-color: red;
    color: blue;
}

Only foreground text color is changed but no change in background in the cell. What is the right way to do this ?

**Comment by gustavnavar** [comment]
Your cant try with the following:

```css
.addPayHold {
    background-color: red !important;
    color: blue;
}
```
