### ISSUE TITLE
Spacing between rows

### ISSUE THREAD

**Issue by taluis** [gustavnavar/Grid.Blazor#60]
How do I narrow the spacing between rows on the grid? I would like less white space. I am new to web development and Blazor so I could us any help.

**Comment by gustavnavar** [comment]
Add this to the ```site.css``` file of your project:
```css
.grid-row {
    line-height: 1.2;
}
```
and check which value works for you.
